### ISSUE TITLE
Version 0.0.4 is absent on plugins.gradle.org

### ISSUE THREAD

**Issue by alexei-osipov** [vontikov/sbe-gradle-plugin#6]
https://plugins.gradle.org/plugin/vontikov.sbe-generator-plugin lists version 0.0.3 as the latest version.
Version 0.0.4 is not present is the Gradle plugin repository.
It would be nice to have a newer version there.

**Comment by vontikov** [comment]
Hi Alexei,

I've published the plugin to https://plugins.gradle.org/plugin/com.github.vontikov.sbe-generator-plugin.
Let me know when I may close the issue.

Vladimir

**Comment by alexei-osipov** [comment]
It's accessible now but it seems that the plugin was compiled using Java 13 so the plugin now requires Java 13+ to run. Is that was intentional change? SBE itself still supports Java 8.

Also plugin ID has changed from `vontikov.sbe-generator-plugin` to `com.github.vontikov.sbe-generator-plugin` (not an issue). Probably it might be a good idea to delete https://plugins.gradle.org/plugin/vontikov.sbe-generator-plugin

**Comment by vontikov** [comment]
I published the [new version](https://github.com/vontikov/sbe-gradle-plugin/releases/tag/v0.0.5), with [minor changes](https://github.com/vontikov/sbe-gradle-plugin/blob/master/RELEASE_NOTES.md), including Java 8 support. Please, take a look.

I could not publish the newer version with the old ID because of changed requirements. I will ask Gradle support to delete https://plugins.gradle.org/plugin/vontikov.sbe-generator-plugin (there is no simple way).
